id = "ps1-theme"
name = "PS1"
version = "0.1.0"
schema_version = 1
authors = ["Owen Carpenter <owen.carpenter@blueconic.com>"]
description = "Retro beige with the classic PlayStation button colors."
repository = "https://github.com/oFrusch/ps1-theme"
